Test add new blocks
wyliodrinstudio/WyliodrinSTUDIO pull request #106
Opened 2023-01-19 12:45 UTC by CAmi307

### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.

### Description of the Change

New blocks dedicated to Raspberry Pi Pico board have been added, allowing interaction between the board and some peripherals like thermistors, servo motors or distance sensors. This PR also contains some new blocks dedicated to Wifi connection and to communication through Wifi.

### Benefits

### Possible Drawbacks

### Applicable Issues

### Format

[ ] ran `npm run electron-format`
[ ] ran `npm run browser-format`

### Author
Signed-off-by: Amalia Camelia Simion<simion.amalia30@gmail.com>

2023-01-19 12:48 UTC, alexandruradovici requested changes

2023-01-19 12:48 UTC, alexandruradovici commented on source/plugins/projects/editor.visual/visual/language_definitions.js
> -
this should not be deleted

2023-01-19 12:48 UTC, alexandruradovici commented on source/plugins/projects/editor.visual/visual/language_python.js
> -	};
This should not be deleted.

2023-01-19 13:30 UTC, CAmi307 commented on source/plugins/projects/editor.visual/visual/language_python.js
> -	};
added it back

2023-01-19 13:32 UTC, CAmi307 commented on source/plugins/projects/editor.visual/visual/language_definitions.js
> -
added it back

2023-01-20 13:05 UTC, alexandruradovici approved these changes

2023-01-22 19:58 UTC, merged